FROM faulo/ci-agent:latest-linux

ARG DEBIAN_FRONTEND=noninteractive

# .NET SDK
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="1"
ENV DOTNET_CLI_UI_LANGUAGE="en"
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt update && \
    apt install -y dotnet-sdk-8.0 && \
    dotnet --version

# DocFX
ENV FrameworkPathOverride="/usr/lib/mono/4.7.1-api/"
RUN apt install -y mono-devel && \
	dotnet tool update -g docfx

# Blender
RUN apt update && apt install -y libxkbcommon-x11-0 jq wget tar xz-utils libglu1-mesa libxi6 libxrender1 libxrandr2 libxcursor1 libxinerama1 libxxf86vm1 && \
    apt clean && rm -rf /var/lib/apt/lists/*
RUN mkdir /blender && \
  if [ -z ${BLENDER_VERSION+x} ]; then \
    BLENDER_VERSION=$(curl -s https://projects.blender.org/api/v1/repos/blender/blender/tags \
      | jq -r '.[] | select(.name | contains("-rc") | not) | .name' \
      | sed 's|^v||g' | sort -rV | head -1); \
  fi && \
  BLENDER_FOLDER=$(echo "Blender${BLENDER_VERSION}" | sed -r 's|(Blender[0-9]*\.[0-9]*)\.[0-9]*|\1|') && \
  curl -o \
    /tmp/blender.tar.xz -fL \
    "https://mirror.clarkson.edu/blender/release/${BLENDER_FOLDER}/blender-${BLENDER_VERSION}-linux-x64.tar.xz" || \
    curl -o \
      /tmp/blender.tar.xz -fL \
      "https://mirrors.iu13.net/blender/release/${BLENDER_FOLDER}/blender-${BLENDER_VERSION}-linux-x64.tar.xz" && \
  tar xf \
    /tmp/blender.tar.xz -C \
    /blender/ --strip-components=1 && \
  ln -s \
    /blender/blender \
    /usr/bin/blender && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*
RUN blender --version

# Unity
RUN echo "deb https://hub.unity3d.com/linux/repos/deb stable main" > /etc/apt/sources.list.d/unityhub.list && \
    wget https://hub.unity3d.com/linux/keys/public -O - | apt-key add - && \
    apt update && \
    apt install -y \
    libgbm-dev \
    libasound2 \
    libgconf-2-4 \
    libtinfo5 \
    libc6-dev \
    libncurses5 \
    libglu1 \
    xvfb \
    cpio \
    p7zip-full \
    ffmpeg \
    python3 \
    apparmor \
    xz-utils \
    unityhub

# Unity 2021 openssl compatibility
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb && \
    dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb && \
    rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb

# VNC Server
ENV USER="root"
ENV RESOLUTION="1920x1080"
RUN apt install -y \
    xfce4 \
    xfce4-goodies \
    tightvncserver \
    dbus-x11 \
    xfonts-base

# Test
RUN compose-unity exec unity-help
