[PHP]
extension=php_exif.dll
extension=php_fileinfo.dll
extension=php_imap.dll
extension=php_intl.dll
extension=php_sockets.dll
extension=php_xsl.dll
extension=php_zip.dll

zend_extension=php_opcache.dll