version: "3.7"

services:
    jenkins:
        container_name: faulo-jenkins        
        image: faulo/jenkins:latest
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        user: root
