FROM jenkins/agent:latest

USER root

# Linux Tools
RUN apt update
RUN apt install -y \
	apt-transport-https \
	wget \
	zip \
	nano \
	gnupg2 \
	ca-certificates \
	software-properties-common \
	curl

# Git
RUN apt install -y \
	git \
	git-lfs

# Plastic
RUN echo "deb https://www.plasticscm.com/plasticrepo/stable/ubuntu/ ./" > /etc/apt/sources.list.d/plasticscm-stable.list
RUN wget https://www.plasticscm.com/plasticrepo/stable/ubuntu/Release.key -O - | apt-key add -
RUN apt update
RUN apt install -y plasticscm-client-core

# NodeJS
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt install -y nodejs

# Linux Tools
RUN apt upgrade -y
