FROM jenkins/jenkins:lts-jdk11

USER root

# Linux Tools
RUN apt update
RUN apt install -y \
	apt-transport-https \
	wget \
	zip \
	nano \
	gnupg2 \
	ca-certificates \
	software-properties-common \
	curl

# Jenkins
RUN mkdir -m 777 /var/workspace
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="1"
ENV JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP=\"\""

# Git
RUN apt install -y git

# Plastic
RUN echo "deb https://www.plasticscm.com/plasticrepo/stable/ubuntu/ ./" > /etc/apt/sources.list.d/plasticscm-stable.list
RUN wget https://www.plasticscm.com/plasticrepo/stable/ubuntu/Release.key -O - | apt-key add -
RUN apt update
RUN apt install -y plasticscm-client-core

# Linux Tools
RUN apt upgrade -y

USER jenkins
