FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# .NET Framework
RUN Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2088631 -OutFile C:\\ndp48-web-installer.exe; \
    Start-Process -FilePath C:\\ndp48-web-installer.exe -ArgumentList '/quiet', '/norestart' -NoNewWindow -Wait; \
    Remove-Item -Force C:\\ndp48-web-installer.exe; \
    if (-not (Test-Path 'HKLM:\\SOFTWARE\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full')) { \
        Write-Error '.NET Framework 4.8 installation failed'; exit 1; \
    }

# Simulate reboot for .NET Framework 4.8
RUN reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager" /v PendingFileRenameOperations /t REG_MULTI_SZ /d ""

# Chocolatey
RUN [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); \
    setx PATH \"${env:PATH};$env:ALLUSERSPROFILE\\chocolatey\\bin\"

# Windows Tools
RUN choco install -y --no-progress \
    zip \
    nano \
    curl
RUN curl.exe --version

# Git
RUN choco install -y --no-progress \
    git
RUN git --version

# Plastic
# TODO

# Docker
ENV DOCKER_HOST=npipe:////./pipe/docker_engine
RUN choco install -y --no-progress \
    docker-cli

# Jenkins
ENV JENKINS_URL=http://jenkins:8080/
ENV JENKINS_SECRET=InsertSecretHere
ENV JENKINS_AGENT_NAME=InsertAgentNameHere
ENV JENKINS_JAVA_OPTS=-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=60
WORKDIR C:\\jenkins
COPY jenkins-agent.bat .
ENTRYPOINT ["cmd", "/c", "C:\\jenkins\\jenkins-agent.bat"]

# Java
ENV JAVA_VERSION=17
ENV JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP=\"\""
RUN choco install -y --no-progress \
    openjdk$env:JAVA_VERSION
RUN java --version
