FROM chocolatey/choco:latest-windows

# Set PowerShell as default shell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Windows Tools
RUN choco install -y --no-progress \
    zip \
    nano \
    curl
RUN curl --version

# Git
RUN choco install -y --no-progress \
    git
RUN git --version

# Plastic
# TODO

# Docker
ENV DOCKER_HOST=npipe:////./pipe/docker_engine
RUN choco install -y --no-progress \
    docker-cli
RUN docker version

# Jenkins
ENV JENKINS_URL=http://jenkins:8080/
ENV JENKINS_SECRET=InsertSecretHere
ENV JENKINS_AGENT_NAME=InsertAgentNameHere
ENV JENKINS_AGENT_WORKDIR=C:\\workspace
ENV JENKINS_JAVA_OPTS=-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=60
WORKDIR C:\\tools
COPY jenkins-agent.bat .
ENTRYPOINT ["cmd", "/c", "jenkins-agent.bat"]

# Java
ENV JAVA_VERSION=17
ENV JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP=\"\""
RUN choco install -y --no-progress \
    openjdk${JAVA_VERSION}
RUN java --version
