name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push unity agent
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: faulo/jenkins-unity:latest
          file: Dockerfile-Unity
      -
        name: Build and push cloud agent
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: faulo/jenkins-agent:latest
          file: Dockerfile-Agent
      -
        name: Build and push host
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: faulo/jenkins-host:latest
          file: Dockerfile-Host
      -
        name: Build and push singleton Jenkins
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: faulo/jenkins:latest
          file: Dockerfile