name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        image: ["basic-agent", "ci-agent", "unity-agent"]
        os: ["linux"]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{secrets.DOCKERHUB_USERNAME}}/${{matrix.image}}:latest-${{matrix.os}}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{matrix.image}}:latest-${{matrix.os}}
          platforms: ${{matrix.os}}/amd64
          context: "{{defaultContext}}:${{matrix.image}}"
          file: Dockerfile
          provenance: false